name: riverpod_example
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  go_router: ^14.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.13

flutter:

  uses-material-design: true
